version: '3.8'
services:
  postgres:
    container_name: listadecompras-container
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ldc-admin
      POSTGRES_PASSWORD: ldc28052018
      POSTGRES_DB: listadecompras-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: